import os

PSYCHIC_SPOON_REDIS_HOST = os.environ.get("PSYCHIC_SPOON_REDIS_HOST", "127.0.0.1")
PSYCHIC_SPOON_REDIS_PORT = int(os.environ.get("PSYCHIC_SPOON_REDIS_PORT", 6379))
PSYCHIC_SPOON_REDIS_DB = int(os.environ.get("PSYCHIC_SPOON_REDIS_DB", 0))
PSYCHIC_SPOON_REDIS_PASSWORD = os.environ.get("PSYCHIC_SPOON_REDIS_PASSWORD")
